spring.application.name=tracker
# ===============================
# Server
# ===============================
server.port=8080

# ===============================
# MySQL Configuration
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/hybrid_shift_tracker?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Shoaib--27

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
